### ISSUE TITLE
Provide information about how to access adminer

### ISSUE THREAD

**Issue by elguitar** [Seravo/wordpress#66] opened 2017-08-10 11:32 UTC
Since the url of adminer differs from WP-palvelu's default url, we should provide information that adminer is found by default in adminer.wordpress.local to avoid confusion.

**Comment by ottok** [comment] 2017-08-10 11:57
This is a duplicate of https://github.com/Seravo/seravo-plugin/issues/28

**Closed** 2017-08-10 11:57 UTC
