### ISSUE TITLE
Log files are not writable or readable

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#53] opened 2017-03-09 13:59 UTC
Running the latest version of this repository and Vagrant box, log files are not readable by vagrant-user, or writable by PHP. 

I added 
```
error_reporting(-1); 
throw new Exception('FATALITY');
```
 to the default theme, which naturally killed the site. Commence debugging: 
```
vagrant@wordpress:~$ tail -f /data/log/php-error.log
tail: cannot open ‘/data/log/php-error.log’ for reading: Permission denied
```
The log file is also empty: 
```
vagrant@wordpress:~$ sudo cat /data/log/php-error.log
vagrant@wordpress:~$
```
Further inspection points to the cause: 
```
vagrant@wordpress:~$ ls -lah /data/log/
total 16K
drwxrwsrwx 2 vagrant vagrant 4.0K Mar  9 13:45 .
drwxr-sr-x 7 vagrant vagrant 4.0K Feb  1 15:23 ..
-rw-r--r-- 1 root    vagrant    0 Feb  1 16:47 error.log
-rw-r--r-- 1 root    vagrant    0 Feb  1 16:47 nginx-access.log
-rw-r--r-- 1 root    vagrant    0 Mar  9 13:45 nginx-error.log
-rw------- 1 root    vagrant    0 Feb  1 16:46 php-error.log
-rw-rw---- 1 redis   vagrant 6.1K Mar  9 13:45 redis.log
```

Running `sudo chown -R vagrant:vagrant /data/log/` will fix this. 

After: 
```
vagrant@wordpress:~$ sudo cat /data/log/php-error.log
[09-Mar-2017 13:56:35 UTC] PHP Fatal error:  Uncaught Exception: FATALITY in /data/wordpress/htdocs/wp-content/themes/twentysixteen/functions.php:36
Stack trace:
#0 /data/wordpress/htdocs/wordpress/wp-settings.php(425): include()
#1 /data/wordpress/htdocs/wp-config.php(123): require_once('/data/wordpress...')
#2 /data/wordpress/htdocs/wordpress/wp-load.php(42): require_once('/data/wordpress...')
#3 /data/wordpress/htdocs/wordpress/wp-blog-header.php(13): require_once('/data/wordpress...')
#4 /data/wordpress/htdocs/index.php(6): require('/data/wordpress...')
#5 {main}
  thrown in /data/wordpress/htdocs/wp-content/themes/twentysixteen/functions.php on line 36
```

**Comment by ottok** [comment] 2017-03-11 20:52
Closing as duplicate of https://github.com/Seravo/wp-palvelu-vagrant/issues/33

**Closed by ottok** 2017-03-11 20:52 UTC
